<?xml version="1.0"?>
<!DOCTYPE dataSourceAttributions [
 <!ELEMENT dataSourceAttributions (dataSourceAttribution+)>
 <!ELEMENT dataSourceAttribution (publications,contacts,displayName,summary,protocol,caveat,acknowledgement,releasePolicy,description,links,wdkReference*)>
 <!ELEMENT publications (publication+)>
 <!ELEMENT publication (#PCDATA)>
 <!ELEMENT contacts (contact+)>
 <!ELEMENT contact (name,email,institution,address,city,state,country,zip)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT email (#PCDATA)>
 <!ELEMENT institution (#PCDATA)>
 <!ELEMENT address (#PCDATA)>
 <!ELEMENT city (#PCDATA)>
 <!ELEMENT state (#PCDATA)>
 <!ELEMENT country (#PCDATA)>
 <!ELEMENT zip (#PCDATA)>
 <!ELEMENT displayName (#PCDATA)>
 <!ELEMENT summary (#PCDATA)>
 <!ELEMENT protocol (#PCDATA)>
 <!ELEMENT caveat (#PCDATA)>
 <!ELEMENT acknowledgement (#PCDATA)>
 <!ELEMENT releasePolicy (#PCDATA)>
 <!ELEMENT description (#PCDATA)>
 <!ELEMENT links (link+)>
 <!ELEMENT link (type,url,linkDescription)>
 <!ELEMENT type (#PCDATA)>
 <!ELEMENT url (#PCDATA)>
 <!ELEMENT linkDescription (#PCDATA)>
 <!ELEMENT wdkReference (#PCDATA)>

<!ATTLIST dataSourceAttribution resource CDATA #REQUIRED>
<!ATTLIST publication pmid CDATA #REQUIRED>
<!ATTLIST contacts isPrimaryContact CDATA #REQUIRED>
<!ATTLIST wdkReference 
          recordClass CDATA #REQUIRED
          type CDATA #REQUIRED 
          name CDATA #REQUIRED
>
]>


<dataSourceAttributions>

  <dataSourceAttribution  resource="">

    <publications>
      <publication pmid=""/>
    </publications>

    <contacts isPrimaryContact="true">
       <contact>
           <name></name>
           <email></email>
           <institution></institution>
           <address></address>
           <city></city>
           <state></state>
           <country></country>
           <zip></zip>
       </contact>
    </contacts>

    <displayName><![CDATA[]]> </displayName>
    <summary><![CDATA[]]></summary>
    <protocol><![CDATA[]]></protocol>
    <caveat><![CDATA[]]></caveat>
    <acknowledgement><![CDATA[]]></acknowledgement>
    <releasePolicy></releasePolicy>
    <description><![CDATA[]]></description>

    <links>
        <link>
           <!-- downloadFile, SupplementartyData, sampleStrategy, publicUrl -->
           <type>downloadFile</type>
           <url><![CDATA[]]></url>
           <linkDescription></linkDescription>
        </link>
    </links>

    <wdkReference recordClass="" type="" name=""/>
  
  </dataSourceAttribution>

</dataSourceAttributions>
