=== EuPathDB-Infra/ApiCommonModel/Model/lib/xml/datasetPresenters/datasetPresenters.dtd
<!ELEMENT datasetPresenters (datasetPresenter+, internalDataset*)>
 <!ELEMENT datasetPresenter (displayName, shortDisplayName?, displayCategory?, summary, description, protocol?, caveat?, acknowledgement?, releasePolicy?, primaryContactId, contactId*, link*, pubmedId*, wdkReference*, templateInjector?)>
 <!ELEMENT displayName (#PCDATA)>
 <!ELEMENT shortDisplayName (#PCDATA)>
 <!ELEMENT displayCategory (#PCDATA)>
 <!ELEMENT summary (#PCDATA)>
 <!ELEMENT description (#PCDATA)>
 <!ELEMENT protocol (#PCDATA)>
 <!ELEMENT caveat (#PCDATA)>
 <!ELEMENT acknowledgement (#PCDATA)>
 <!ELEMENT releasePolicy (#PCDATA)>
 <!ELEMENT primaryContactId (#PCDATA)>
 <!ELEMENT contactId (#PCDATA)>
 <!ELEMENT link (text?,url)>
 <!ELEMENT text (#PCDATA)>
 <!ELEMENT url (#PCDATA)>
 <!ELEMENT pubmedId (#PCDATA)>
 <!ELEMENT wdkReference (#PCDATA)>
 <!ELEMENT templateInjector (prop)>
 <!ELEMENT prop (#PCDATA)>
 <!ELEMENT internalDataset (#PCDATA)>

<!ATTLIST datasetPresenter name CDATA #REQUIRED>
<!ATTLIST datasetPresenter projectName CDATA #IMPLIED>
<!ATTLIST datasetPresenter buildNumberIntroduced CDATA #IMPLIED>
<!ATTLIST datasetPresenter datasetNamePattern CDATA #IMPLIED>
<!ATTLIST wdkReference
          recordClass CDATA #REQUIRED
          type CDATA #REQUIRED
          name CDATA #REQUIRED
>
<!ATTLIST internalDataset name CDATA #REQUIRED>
<!ATTLIST internalDataset datasetNamePattern CDATA #IMPLIED>

=== EuPathDB-Infra/ApiCommonModel/Model/lib/xml/datasetPresenters/GiardiaDB.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="datasetPresenters.xslt"?>
<!DOCTYPE datasetPresenters SYSTEM "datasetPresenters.dtd">
<datasetPresenters>

<!--
  <datasetPresenter name=""
                    projectName="GiardiaDB"
                    >
    <displayName><![CDATA[
    ]]></displayName>
    <shortDisplayName></shortDisplayName>
    <displayCategory>Genomes and Annotation:Organellar</displayCategory>
    <summary><![CDATA[
    ]]></summary>
    <description><![CDATA[
    ]]></description>
    <protocol></protocol>
    <caveat></caveat>
    <acknowledgement></acknowledgement>
    <releasePolicy></releasePolicy>
    <primaryContactId></primaryContactId>
    <link>
      <text></text>
      <url></url>
    </link>
    <pubmedId></pubmedId>
    <templateInjector className=""/>

  </datasetPresenter>
-->

  <datasetPresenter name="gassAWB_primary_genome_RSRC"
                    projectName="GiardiaDB"
                    >
    <displayName><![CDATA[G. lamblia Assemblage A sequence and annotation from Genbank]]></displayName>
    <shortDisplayName></shortDisplayName>
    <displayCategory>Genomes and Annotation</displayCategory>
    <summary><![CDATA[
    ]]></summary>
    <description><![CDATA[
G. lamblia sequence, assembly, annotation from Mitchell Sogin(MBL).<br /><br />
            Genomic minimalism in the early diverging intestinal parasite Giardia lamblia.
            cd Hilary G. Morrison, Andrew G. McArthur, Frances D. Gillin, Stephen B. Aley, Rodney D. Adam, 
            Gary J. Olsen, Aaron A. Best, W. Zacheus Cande, Feng Chen, Michael J. Cipriano, Barbara J. Davids, 
            Scott C. Dawson, Heidi G. Elmendorf, Adrian B. Hehl, Michael E. Holder, Susan M. Huse, Ulandt U. Kim, 
            Erica Lasek-Nesselquist, Gerard Manning, Anuranjini Nigam, Julie E. J. Nixon, Daniel Palm, 
            Nora E. Passamaneck, Anjali Prabhu, Claudia I. Reich, David S. Reiner, John Samuelson, 
            Staffan G. Svard, and Mitchell L. Sogin
            Science 28 September 2007, Volume 317, pp. 1921-1926.
    ]]></description>
    <protocol></protocol>
    <caveat></caveat>
    <acknowledgement></acknowledgement>
    <releasePolicy></releasePolicy>
    <primaryContactId>hilary.morrison</primaryContactId>
    <pubmedId>17901334</pubmedId>
    <templateInjector className="org.apidb.apicommon.model.datasetInjector.AnnotatedGenome"/>

  </datasetPresenter>

  <datasetPresenter name="gassBGS_primary_genome_RSRC"
                    projectName="GiardiaDB"
                    >
    <displayName><![CDATA[G. intestinalis Assemblage B sequence and annotation from Genbank
    ]]></displayName>
    <shortDisplayName></shortDisplayName>
    <displayCategory>Genomes and Annotation:Organellar</displayCategory>
    <summary><![CDATA[
    ]]></summary>
    <description><![CDATA[
Draft Genome Sequencing of Giardia intestinalis Assemblage B Isolate GS: Is Human Giardiasis Caused by Two Different Species ? Franzen O, Jerlstrom-Hultqvist J, Castro E, Sherwood E, Ankarklev J, Reiner DS, Palm D, Andersson JO, Andersson B, Svard SG.
    ]]></description>
    <protocol></protocol>
    <caveat></caveat>
    <acknowledgement></acknowledgement>
    <releasePolicy></releasePolicy>
    <primaryContactId>staffan.svard</primaryContactId>
    <link>
      <text></text>
      <url></url>
    </link>
    <pubmedId>19696920</pubmedId>
    <templateInjector className="org.apidb.apicommon.model.datasetInjector.AnnotatedGenome"/>

  </datasetPresenter>


  <datasetPresenter name="gassEP15_primary_genome_RSRC"
                    projectName="GiardiaDB"
                    >
    <displayName><![CDATA[G. intestinalis Assemblage E sequence and annotation from Genbank
    ]]></displayName>
    <shortDisplayName></shortDisplayName>
    <displayCategory>Genomes and Annotation:Organellar</displayCategory>
    <summary><![CDATA[
    ]]></summary>
    <description><![CDATA[
Sequence and annotation of Giardia Assemblage E isolate P15 was provided by J. Jerlstrom-Hultqvist. O. Franzen, E. Castro, J. Ankarklev, D. Palm, J. O. Andersson, S.G. Svard and B. Andersson (Karolinska Institutet, Stockholm, Sweden and Uppsala University, Uppsala, Sweden). The genome sequence and annotation was provided to GiardiaDB prepublication and is expected to be published in a peer-reviewed journal as soon as possible. Permission should be obtained from the authors before publishing analyses of the sequence/open reading frames/genes on a chromosome or genome scale.
    ]]></description>
    <protocol></protocol>
    <caveat></caveat>
    <acknowledgement></acknowledgement>
    <releasePolicy></releasePolicy>
    <primaryContactId>staffan.svard</primaryContactId>
    <link>
      <text></text>
      <url></url>
    </link>
    <pubmedId>20929575</pubmedId>
    <templateInjector className="org.apidb.apicommon.model.datasetInjector.AnnotatedGenome"/>

  </datasetPresenter>
  <datasetPresenter name="gassAWB_primary_virtual_genome_RSRC"
                    projectName="GiardiaDB"
                    >
    <displayName><![CDATA[G. lamblia Assemblage A scaffold to chromosome map
    ]]></displayName>
    <shortDisplayName></shortDisplayName>
    <displayCategory>Genomes and Annotation:Organellar</displayCategory>
    <summary><![CDATA[
    ]]></summary>
    <description><![CDATA[
An MluI optical map of the WB genome was generated.  Scaffolds and contigs were mapped to the optical map and assembled into chromsomes.  <br><br>
Optical map of the Genotype A1 WB C6 Giardia lamblia genome isolate. Alexander D Perry, Hilary G Morrison, Rodney D Adam.

    ]]></description>
    <protocol></protocol>
    <caveat></caveat>
    <acknowledgement></acknowledgement>
    <releasePolicy></releasePolicy>
    <primaryContactId>rod.adam</primaryContactId>

    <pubmedId>21835210</pubmedId>
    <templateInjector className="org.apidb.apicommon.model.datasetInjector.AnnotatedGenome"/>

  </datasetPresenter>


  <!-- TODO: Microarray to DATASETPRESENTERS -->
  <internalDataset name="gassAWB_microarrayExpression_Hehl_Stress-response_Incubation_RSRC"/>
  <internalDataset name="gassAWB_microarrayExpression_Hehl_Stress-response_Temperature_Concentration_RSRC"/>
  <internalDataset name="gassAWB_microarrayExpression_Ringqvist_RSRC"/>
  <internalDataset name="gassAWB_microarrayExpression_Hehl_Encystation_RSRC"/>
  <internalDataset name="gassAWB_microarrayExpression_Troell_RSRC"/>

  <!-- TODO: RNASeq to DATASETPRESENTERS -->
  <internalDataset name="gassAWB_Svard_rnaSeq_RSRC"/>

  <!-- TODO: one of these to DATASETPRESENTERS -->
  <internalDataset name="gassAWB_sageTag_McArthurSageTags_frequencies_RSRC"/>
  <internalDataset name="gassAWB_sageTag_McArthurSageTags_RSRC"/>

  <!-- TODO: proteomics to DATASETPRESENTERS -->
  <internalDataset name="gassAWB_massSpec_Gillin_Proteomics_RSRC"/>
  <internalDataset name="gassAWB_massSpec_Tachezy_Enriched_Fraction_RSRC"/>
  <internalDataset name="gassAWB_massSpec_Ratner_DTASelect-filter_RSRC"/>


  <!-- Optional TODO... provide attribution for microarray platforms -->
  <internalDataset name="gassAWB_microarrayPlatform_Troell_RSRC"/>
  <internalDataset name="gassAWB_microarrayPlatform_Giardia_Lamblia_RSRC"/>

  <!-- No attribution needed below here -->
  <internalDataset name="gassBGS_previousProteinId_NAFeature_aliases_RSRC"/>
  <internalDataset name="gassAWB_dbxref_gene2Deprecated_RSRC"/>
  <internalDataset name="gassAWB_ScaffoldSequenceIDs_NASequence_aliases_RSRC"/>
  <internalDataset name="gassAWB_ContigSequenceIDs_NASequence_aliases_RSRC"/>
  <internalDataset name="gassAWB_secondary_virtual_genome_RSRC"/>



</datasetPresenters>

=== EuPathDB-Infra/ApiCommonModel/Model/lib/xml/datasetPresenters/HostDB.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="datasetPresenters.xslt"?>
<!DOCTYPE datasetPresenters SYSTEM "datasetPresenters.dtd">
<datasetPresenters>

  <datasetPresenter name="hsapREF_primary_genome_RSRC"
                    projectName="HostDB"
                    buildNumberIntroduced="18"
                    >
    <displayName>Genome Sequence and Annotation</displayName>
    <shortDisplayName>Human Genome</shortDisplayName>
    <displayCategory></displayCategory>
    <summary></summary>
    <description></description>
    <protocol></protocol>
    <caveat></caveat>
    <acknowledgement></acknowledgement>
    <releasePolicy></releasePolicy>
    <primaryContactId>TODO</primaryContactId>
    <link>
      <text>This directory contains the Feb. 2009 assembly of the human genome (hg19,
			GRCh37 Genome Reference Consortium Human Reference 37 (GCA_000001405.1))
			in one gzip-compressed FASTA file per chromosome.
			</text>
      <url>ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes/</url>
    </link>
    <pubmedId></pubmedId>
  </datasetPresenter>

  <datasetPresenter name="hsapREF_Gregory_ME49_mRNA_rnaSeq_RSRC"
                    projectName="HostDB"
                    buildNumberIntroduced="18"
                    >
    <displayName>Tachyzoite Post Infection Time Series</displayName>
    <shortDisplayName>Time Series</shortDisplayName>
    <displayCategory></displayCategory>
    <summary></summary>
    <description></description>
    <protocol></protocol>
    <caveat></caveat>
    <acknowledgement></acknowledgement>
    <releasePolicy></releasePolicy>
    <primaryContactId>TODO</primaryContactId>
    <link>
      <text></text>
      <url></url>
    </link>
    <pubmedId></pubmedId>
  </datasetPresenter>

 <!-- <internalDataset name="hsapREF_primary_genome_RSRC"/> -->
 <!-- <internalDataset name="hsapREF_Gregory_ME49_mRNA_rnaSeq_RSRC"/> -->
 <internalDataset name="hsapREF_ucscId_NAFeature_aliases_RSRC"/>
 <internalDataset name="hsapREF_havanaGeneId_NAFeature_aliases_RSRC"/>
 <internalDataset name="hsapREF_havanaTranscriptId_NAFeature_aliases_RSRC"/>
 <internalDataset name="hsapREF_transcriptId_NAFeature_aliases_RSRC"/>
 <internalDataset name="hsapREF_genome_gencode_RSRC"/>

</datasetPresenters>
